version: "3.3"
services:
  lojza-mongo:
    container_name: lojza-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lojza
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - "mongo-volume:/data/db"
    networks:
      - lojza
    image: mongo:latest
  lojza:
    container_name: lojza
    restart: always
    environment:
      - DISCORD_TOKEN=your_epic_token
      - MONGO_PASSWORD=12345678
      - MONGO_SERVER=lojza-mongo
    networks:
      - lojza
    image: jsfraz/lojza:1.0.0
volumes:
  mongo-volume:
    external: false
networks:
  lojza:
    name: lojza